name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_torochallenge-frontend:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'torochallenge-frontend' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker build .
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
